package:
  name: sospex
  version: 0.5.beta

source:
  git_tag: python3
  git_url: https://github.com/darioflute/sospex.git

build:
  
requirements:
  build:
    - python
    - setuptools

  run:
    - python 
    - numpy >=1.12.1
    - astropy >=2.0.2
    - matplotlib >=2.1.0
        
test:
  imports:
    - sospex

about:
  home: https://github.com/darioflute/sospex
  license: GPL3
  license_file: LICENSE
  description: 'The package displays FIFI-LS and GREAT spectral cubes'
