package:
  name: sospex
  version: 0.34.beta

source:
  git_tag: master
  git_url: https://github.com/darioflute/sospex.git

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  
requirements:
  host:
    - pip
    - python
    - setuptools


  run:
    - python
        
test:
  imports:
    - sospex

about:
  home: https://github.com/darioflute/sospex
  license: GPL3
  license_file: LICENSE
  description: 'The package displays FIFI-LS and GREAT spectral cubes'
