{% set name = "sospex" %}
#{% set version = "0.36b0" %}
{% set data = load_setup_py_data() %}


package:
  name: "{{ name|lower }}"
  version: "{{ data.get('version') }}"

source:
  git_tag: master
  git_url: https://github.com/darioflute/sospex.git

build:
  
requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - matplotlib >=3.0.2
    - numpy >=1.11
    - scipy
    - astropy >=3.0
        
test:
  imports:
    - sospex

about:
  home: https://github.com/darioflute/sospex
  license: GPL3
  license_file: LICENSE
  description: 'The package displays FIFI-LS and GREAT spectral cubes'
