package:
  name: sospex
  version: 0.33.beta

source:
  git_tag: master
  git_url: https://github.com/darioflute/sospex.git

build:
  
requirements:
  build:
    - python
    - setuptools

  run:
    - python >=3.6
    - numpy >=1.11
    - astropy >=3.0
    - matplotlib >=2.1,<3.0
        
test:
  imports:
    - sospex

about:
  home: https://github.com/darioflute/sospex
  license: GPL3
  license_file: LICENSE
  description: 'The package displays FIFI-LS and GREAT spectral cubes'
