{% set name = "sospex" %}
{% set version = "0.34b0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_tag: master
  git_url: https://github.com/darioflute/sospex.git

build:
  number: 0
  
requirements:
  host:
  build:
    - setuptools
    - python >=3.6

  run:
    - python >=3.6
    - matplotlib >=3.0.2
    - numpy >=1.11
    - scipy
    - astropy >=3.0
        
test:
  imports:
    - sospex

about:
  home: https://github.com/darioflute/sospex
  license: GPL3
  license_file: LICENSE
  description: 'The package displays FIFI-LS and GREAT spectral cubes'
