package:
  name: sospex
  version: 0.1.alpha

source:
  git_rev: v0.1-alpha
  git_url: https://github.com/darioflute/sospex.git

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - astropy >=1.2.1
    - scipy
    - wxpython

    
test:
  imports:
    - sospex

about:
  home: https://github.com/darioflute/sospex
  license: GPL3
  license_file: LICENSE
  description: 'The package displays FIFI-LS spectral cubes'
