package:
  name: sospex
  version: 0.34.beta

source:
  git_tag: master
  git_url: https://github.com/darioflute/sospex.git

build:
  
requirements:
  host:
  
  build:
    - setuptools
    - python >=3.6
    - numpy >=1.11
    - matplotlib >=3.0.2
    - scipy
    - astropy >=3.0

  run:
    - python >=3.6
    - matplotlib >=3.0.2
    - numpy >=1.11
    - scipy
    - astropy >=3.0
        
test:
  imports:
    - sospex

about:
  home: https://github.com/darioflute/sospex
  license: GPL3
  license_file: LICENSE
  description: 'The package displays FIFI-LS and GREAT spectral cubes'
