package:
  name: sospex
  version: 0.8.alpha

source:
  git_rev: v0.8-alpha
  git_url: https://github.com/darioflute/sospex.git

build:
  script:
    -python setup.py install
  
requirements:
  build:
    - python
    - setuptools
    - matplotlib
    - numpy

  run:
    - python
    - numpy
    - astropy >=1.2.1
    - scipy
    - matplotlib
    - wxpython
    
    
test:
  imports:
    - sospex

about:
  home: https://github.com/darioflute/sospex
  license: GPL3
  license_file: LICENSE
  description: 'The package displays FIFI-LS spectral cubes'
